server:
    port: 9090
management:
    port: 9091
    address: 127.0.0.1
http:
    mappers: 
       jsonPrettyPrint: true
spring:
      main:
           banner-mode: OFF
      data:
        rest:
          base-path: /api
          
logging:
        file: /tmp/spring-boot-mvc-data-rest.log
