﻿server:
    port: 9090
management:
    port: 9091
http:
    mappers: 
       jsonPrettyPrint: true
spring:
      main:
           banner-mode: OFF

logging:
        file: /tmp/spring-boot-mvc-rest.log