http:
        mappers: 
            jsonPrettyPrint: true
        
logging:
        level:
            org.springframework.web: ERROR
            org.hibernate: ERROR
            level.org.hibernate: ERROR
            com.mylab: DEBUG
            
endpoints:
        shutdown.enabled: true