spring:
    profiles:
        active: production
        
---

spring:
    profiles: development
    
    mail: 
          host: localhost
          port: 3600
    
    datasource:
          platform: hsqldb
          mail: 
          host: localhost
          port: 3600

server:
        port: 9090
        contextPath: /pizza
        session-timeout: 10000
management:
        port: 9091
        address: 127.0.0.1
        context-path: /manage2
        security: 
              enabled: true
              role: ADMIN
http:
        mappers: 
        jsonPrettyPrint: true
        
logging:
        level:
            org.springframework.web: ERROR
            org.hibernate: ERROR
            level.org.hibernate: ERROR
            com.mylab: DEBUG
            
endpoints:
         shutdown.enabled: true

---
spring:
    profiles: production
    
    spring:
          datasource:
                jndi-name: java:jboss/datasources/pizzas
    
    mail: 
          host: localhost
          port: 3600
    
    datasource:
          platform: hsqldb
          mail: 
          host: localhost
          port: 3600

server:
        port: 9090
        contextPath: /pizza
        session-timeout: 10000
management:
        port: 9091
        address: 127.0.0.1
        context-path: /manage
        security: 
              enabled: true
              role: ADMIN
http:
        mappers: 
        jsonPrettyPrint: true
        
logging:
        level:
            org.springframework.web: ERROR
            org.hibernate: ERROR
            level.org.hibernate: ERROR
            com.mylab: DEBUG
            
endpoints:
         shutdown.enabled: true