http:
        mappers: 
            jsonPrettyPrint: true
        
logging:
        level:
            org.springframework.web: DEBUG
            org.hibernate: DEBUG
            level: DEBUG
            com.mylab: DEBUG
            org.apache.tiles: DEBUG
endpoints:
        shutdown.enabled: true