spring:
    profiles: inte   
    mail: 
          host: localhost
          port: 3600
    
    spring.datasource:
          platform: hsqldb
          mail: 
          host: localhost
          port: 3600
server:
        port: 9098
        contextPath: /pizza
        session-timeout: 10000
management:
        port: 9099
        address: 127.0.0.1
        context-path: /manage2
        security: 
              enabled: true
              role: ADMIN
http:
        mappers: 
        jsonPrettyPrint: true
        
logging:
        level:
            org.springframework.web: ERROR
            org.hibernate: ERROR
            level.org.hibernate: ERROR
            com.mylab: DEBUG
            
endpoints:
         shutdown.enabled: true